
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import * as XLSX from 'xlsx';
import html2canvas from 'html2canvas';
import { Grievance, IssueStatus } from '../types';

export const downloadService = {
  /**
   * Generates a high-fidelity PDF Audit following the 10-point structural requirement.
   */
  async exportGrievancePDF(g: Grievance, exportedBy: string = 'System') {
    const doc = new jsPDF() as any;
    const timestamp = new Date().toLocaleString();
    
    // 1. Platform Branding & Header
    doc.setFillColor(15, 23, 42); // Slate-900
    doc.rect(0, 0, 210, 45, 'F');
    
    doc.setTextColor(59, 130, 246); // Blue-500
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('CivicConnect™', 14, 25);
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.text('Smart City Oversight & ResolveChain™ Technology', 14, 32);
    
    // 2. Report Title & 3. Date/Time
    doc.setFontSize(14);
    doc.text('MUNICIPAL CASE AUDIT REPORT', 120, 25);
    doc.setFontSize(8);
    doc.text(`Generated: ${timestamp}`, 120, 32);
    doc.text(`Authenticated for: ${exportedBy}`, 120, 37);

    // 4. Case Identification
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('AUDIT IDENTIFICATION', 14, 60);
    doc.setFont('helvetica', 'normal');
    doc.text(`Case ID: ${g.id}`, 14, 66);
    doc.text(`IssueDNA™: ${g.dnaSignature}`, 14, 71);

    // 5. Complaint Details
    doc.setFont('helvetica', 'bold');
    doc.text('CASE NARRATIVE', 14, 85);
    doc.setFont('helvetica', 'normal');
    doc.text(`Title: ${g.title}`, 14, 91);
    doc.text(`Category: ${g.category}`, 14, 96);
    
    const splitDesc = doc.splitTextToSize(g.description, 180);
    doc.text(splitDesc, 14, 101);

    // 6. Location & 7. Status & 8. Priority
    doc.setFont('helvetica', 'bold');
    doc.text('FIELD PARAMETERS', 14, 130);
    doc.setFont('helvetica', 'normal');
    doc.text(`Location: ${g.location.address || 'N/A'}`, 14, 136);
    doc.text(`Status: ${g.status}`, 14, 141);
    doc.text(`Stress Index (Priority): ${g.priority}`, 14, 146);

    // 9. ResolveChain™ Events (Resolution Details)
    doc.setFont('helvetica', 'bold');
    doc.text('RESOLVECHAIN™ IMMUTABLE LOG', 14, 160);
    
    const tableData = g.resolveChain.map(event => [
      new Date(event.timestamp).toLocaleString(),
      event.status,
      event.action,
      event.actor
    ]);

    doc.autoTable({
      startY: 165,
      head: [['Timestamp', 'Phase', 'Action', 'Entity']],
      body: tableData,
      theme: 'striped',
      headStyles: { fillColor: [59, 130, 246] },
      styles: { fontSize: 8 }
    });

    // 10. Proprietary Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.text('This document is a legally recognized electronic record generated by CivicConnect Command OS. Verify DNA signatures at civicconnect.gov/verify.', 14, pageHeight - 10);
    
    doc.save(`Audit_${g.id}_${g.dnaSignature}.pdf`);
  },

  /**
   * Professional Excel Export with proper alignment and column mapping.
   */
  exportGrievancesExcel(data: Grievance[], filename = 'City_Health_Ledger.xlsx') {
    const worksheetData = data.map(g => ({
      'Audit ID': g.id,
      'IssueDNA™ Signature': g.dnaSignature,
      'Report Date': new Date(g.createdAt).toLocaleString(),
      'Title': g.title,
      'Category': g.category,
      'Priority': g.priority,
      'Current Status': g.status,
      'Location Address': g.location?.address || 'N/A',
      'Area/Ward': g.location?.area || 'N/A',
      'Community Upvotes': g.upvotes,
      'Impact Score': (g.upvotes * 10) + 50
    }));

    const worksheet = XLSX.utils.json_to_sheet(worksheetData);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Municipal Logs');

    // Auto-fit columns (simulated)
    const wscols = Object.keys(worksheetData[0]).map(() => ({ wch: 20 }));
    worksheet['!cols'] = wscols;

    XLSX.writeFile(workbook, filename);
  },

  /**
   * High-Resolution Card Capture for Social and Personal Records.
   */
  async captureSnapshot(elementId: string, filename = 'Civic_Snapshot.png') {
    const element = document.getElementById(elementId);
    if (!element) return;
    
    const canvas = await html2canvas(element, {
      backgroundColor: '#f8fafc',
      scale: 3, // Ultra-high-def for viva/project presentations
      logging: false,
      useCORS: true,
      windowWidth: element.scrollWidth,
      windowHeight: element.scrollHeight
    });
    
    const link = document.createElement('a');
    link.download = filename;
    link.href = canvas.toDataURL('image/png');
    link.click();
  }
};
